-- Insert GHN Provinces (Tỉnh/Thành phố)
INSERT INTO public.ghn_provinces (province_id, province_name, province_name_en, is_active) VALUES
(1, 'Hà Nội', 'Ha Noi', true),
(2, 'Hà Giang', 'Ha Giang', true),
(3, 'Quảng Ninh', 'Quang Ninh', true),
(4, 'Cao Bằng', 'Cao Bang', true),
(5, 'Yên Bái', 'Yen Bai', true),
(6, 'Bắc Giang', 'Bac Giang', true),
(7, 'Bắc Kạn', 'Bac Kan', true),
(8, 'Tuyên Quang', 'Tuyen Quang', true),
(9, 'Lạng Sơn', 'Lang Son', true),
(10, 'Lào Cai', 'Lao Cai', true),
(11, 'Điện Biên', 'Dien Bien', true),
(12, 'Lai Châu', 'Lai Chau', true),
(14, 'Hòa Bình', 'Hoa Binh', true),
(15, 'Hải Phòng', 'Hai Phong', true),
(16, 'Vĩnh Phúc', 'Vinh Phuc', true),
(17, 'Thái Nguyên', 'Thai Nguyen', true),
(18, 'Hải Dương', 'Hai Duong', true),
(19, 'Thái Bình', 'Thai Binh', true),
(20, 'Hà Nam', 'Ha Nam', true),
(21, 'Nam Định', 'Nam Dinh', true),
(22, 'Nghệ An', 'Nghe An', true),
(23, 'Hà Tĩnh', 'Ha Tinh', true),
(24, 'Sơn La', 'Son La', true),
(25, 'Khánh Hòa', 'Khanh Hoa', true),
(26, 'Phú Thọ', 'Phu Tho', true),
(27, 'Phú Yên', 'Phu Yen', true),
(28, 'Kon Tum', 'Kon Tum', true),
(30, 'Gia Lai', 'Gia Lai', true),
(33, 'Đắk Lắk', 'Dak Lak', true),
(34, 'Đắk Nông', 'Dak Nong', true),
(35, 'Lâm Đồng', 'Lam Dong', true),
(36, 'Ninh Thuận', 'Ninh Thuan', true),
(37, 'Bình Phước', 'Binh Phuoc', true),
(38, 'Thanh Hóa', 'Thanh Hoa', true),
(40, 'Quảng Bình', 'Quang Binh', true),
(41, 'Quảng Trị', 'Quang Tri', true),
(42, 'Thừa Thiên Huế', 'Thua Thien Hue', true),
(44, 'Quảng Nam', 'Quang Nam', true),
(45, 'Quảng Ngãi', 'Quang Ngai', true),
(48, 'Đà Nẵng', 'Da Nang', true),
(49, 'Bình Định', 'Binh Dinh', true),
(51, 'Gia Lai', 'Gia Lai', true),
(52, 'Bình Thuận', 'Binh Thuan', true),
(54, 'Bình Dương', 'Binh Duong', true),
(55, 'Tây Ninh', 'Tay Ninh', true),
(56, 'Đồng Nai', 'Dong Nai', true),
(57, 'Bà Rịa Vũng Tàu', 'Ba Ria Vung Tau', true),
(58, 'TP. Hồ Chí Minh', 'Ho Chi Minh', true),
(59, 'Long An', 'Long An', true),
(60, 'Tiền Giang', 'Tien Giang', true),
(61, 'Bến Tre', 'Ben Tre', true),
(62, 'Trà Vinh', 'Tra Vinh', true),
(63, 'Vĩnh Long', 'Vinh Long', true),
(64, 'Đồng Tháp', 'Dong Thap', true),
(65, 'An Giang', 'An Giang', true),
(66, 'Kiên Giang', 'Kien Giang', true),
(67, 'Cần Thơ', 'Can Tho', true),
(68, 'Hậu Giang', 'Hau Giang', true),
(69, 'Sóc Trăng', 'Soc Trang', true),
(70, 'Bạc Liêu', 'Bac Lieu', true),
(71, 'Cà Mau', 'Ca Mau', true);

-- Insert GHN Districts (Quận/Huyện) - Chỉ lấy mẫu cho Hà Nội và TP.HCM
-- Hà Nội (province_id = 1)
INSERT INTO public.ghn_districts (province_id, district_id, district_name, district_type, is_active) VALUES
(1, 1, 'Hoàn Kiếm', 'Quận', true),
(1, 2, 'Ba Đình', 'Quận', true),
(1, 3, 'Tây Hồ', 'Quận', true),
(1, 4, 'Thanh Xuân', 'Quận', true),
(1, 5, 'Cầu Giấy', 'Quận', true),
(1, 6, 'Đống Đa', 'Quận', true),
(1, 7, 'Hai Bà Trưng', 'Quận', true),
(1, 8, 'Hoàng Mai', 'Quận', true),
(1, 9, 'Long Biên', 'Quận', true),
(1, 10, 'Bắc Từ Liêm', 'Quận', true),
(1, 11, 'Nam Từ Liêm', 'Quận', true),
(1, 1455, 'Hà Đông', 'Quận', true);

-- TP. Hồ Chí Minh (province_id = 58)
INSERT INTO public.ghn_districts (province_id, district_id, district_name, district_type, is_active) VALUES
(58, 1, 'Quận 1', 'Quận', true),
(58, 3, 'Quận 3', 'Quận', true),
(58, 4, 'Quận 4', 'Quận', true),
(58, 5, 'Quận 5', 'Quận', true),
(58, 6, 'Quận 6', 'Quận', true),
(58, 7, 'Quận 7', 'Quận', true),
(58, 8, 'Quận 8', 'Quận', true),
(58, 10, 'Quận 10', 'Quận', true),
(58, 11, 'Quận 11', 'Quận', true),
(58, 12, 'Quận 12', 'Quận', true),
(58, 201, 'Bình Thạnh', 'Quận', true),
(58, 202, 'Gò Vấp', 'Quận', true),
(58, 203, 'Phú Nhuận', 'Quận', true),
(58, 204, 'Tân Bình', 'Quận', true),
(58, 205, 'Tân Phú', 'Quận', true),
(58, 206, 'Thủ Đức', 'Quận', true);

-- Insert GHN Wards (Phường/Xã) - Mẫu cho Hà Đông Hà Nội
INSERT INTO public.ghn_wards (province_id, district_id, ward_code, ward_name, is_active) VALUES
(1, 1455, '21617', 'Phúc Diễn', true),
(1, 1455, '21618', 'Dương Nội', true),
(1, 1455, '21619', 'Hà Cầu', true),
(1, 1455, '21620', 'Quang Trung', true),
(1, 1455, '21621', 'Tân Mai', true),
(1, 1455, '21622', 'Tây Mỗ', true),
(1, 1455, '21623', 'Thanh Mỹ', true),
(1, 1455, '21624', 'Triều Khúc', true);

-- Mẫu wards cho Quận 1 TP.HCM
INSERT INTO public.ghn_wards (province_id, district_id, ward_code, ward_name, is_active) VALUES
(58, 1, '13000', 'Bến Nghé', true),
(58, 1, '13001', 'Bến Thành', true),
(58, 1, '13002', 'Cầu Ông Lãnh', true),
(58, 1, '13003', 'Đa Kao', true),
(58, 1, '13004', 'Nguyễn Huệ', true),
(58, 1, '13005', 'Tân Định', true);
